title: Bingzhou Li's Homepage
page-top-title: Bingzhou Li
top-section-bg-text: Computer Science and Technology
home-subtitle: Bingzhou Li&ensp;|&ensp;李秉洲
copyright-text: '&copy; Bingzhou Li 2023-2026. All Rights Reserved.'
